CREATE DATABASE IF NOT EXISTS dbtallas;
USE dbtallas;

CREATE TABLE IF NOT EXISTS tallas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    relacion VARCHAR(150) NOT NULL,
    prenda VARCHAR(100) NOT NULL,
    talla VARCHAR(20) NOT NULL,
    notas TEXT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);


